name: ci

on:
  pull_request:
    branches: [main]


jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Force Failure
        run: go test --cover ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check go formatting
        run: test -z $(go fmt ./...)

      - name: Linting
        run: statickcheck ./...
